---
- name: docker images build & push
  hosts: master
  become: no


  tasks:
  - name: index.html delivery
    become: yes
    copy:
      src: index.html
      dest: /root/index.html
        
  - name: index.html delivery
    become: yes
    copy:
      src: companyname.html
      dest: /root/companyname


  - name: docker images build & push & rolling-update  
    shell: ./docker-images-build.sh
      


